#=================== Web应用参数配置 开始 =========================
#项目访问端口号配置
server.port=8118
#项目访问路径配置。当HTML页面引入JS等静态文件使用绝对路径时，请不要更改该参数，免得静态文件引入失败。
server.servlet.context-path=/
#设置session超时时间
server.servlet.session.timeout=PT10H
#将该系统属性设置为true，跳过扫描BeanInfo类，防止重复加载bean。默认值本来就是true。
spring.beaninfo.ignore=true
#HTTP报文编码配置。不配置会导致中文字符会出现乱码。
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
spring.banner.charset=UTF-8
spring.messages.encoding=UTF-8
server.tomcat.uri-encoding=UTF-8

#文件上传大小
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=50MB
#解码URI时指定UTF-8编码
server.tomcat.uri-encoding=UTF-8
server.tomcat.max-http-post-size=-1
spring.banner.charset=UTF-8
spring.messages.encoding=UTF-8
#项目名称
project.name=igw-m-portal

#consul
spring.application.name=portal-Server
#consul-host
spring.cloud.consul.host=10.86.130.109
#consul-port
spring.cloud.consul.port=8500

#健康检测的url
spring.cloud.consul.discovery.health-check-path=/health
# 健康检测时间间隔
spring.cloud.consul.discovery.health-check-interval=10s
#设置 服务名称
spring.cloud.consul.discovery.service-name=portal-Server-test
#是否去发现其他服务
spring.cloud.consul.discovery.heartbeat.enabled=true
#设置注册服务 使用服务器ip
spring.cloud.consul.discovery.prefer-ip-address=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

feign.hystrix.enabled=false


#=================== Web应用参数配置 结束 =========================

#=================== tomcat accessLog配置 开始 =========================
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.directory=${igw.log.output.dir}/tomcat-accesslog
server.tomcat.accesslog.rotate=true
server.tomcat.accesslog.pattern='%t %a %A %m %U%q %s %D %I %B'
server.tomcat.accesslog.buffered=false
#=================== tomcat accessLog配置 结束 =========================

#=================== Mybatis配置 开始 =========================
#启用SpringBoot的Mybatis自动配置时，启用该配置项
mybatis.mapper-locations=classpath:com/igw/**/dao/**.xml,classpath:mapping/**.xml
mybatis.type-aliases-package=com.igw.market.**.domain
#=================== Mybatis配置 结束 =========================

#=================== Spring MVC配置 开始 =========================
#Controler返回的View路径补全
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
#静态资源访问路径
spring.mvc.static-path-pattern=/**
#静态资源映射路径
#默认值。不进行配置时自动使用该值。
#spring.resources.static-locations=classpath:/static


#静态资源映射路径
#默认配置（按优先级排序）： classpath:/META-INF/resources,classpath:/resources,classpath:/static,classpath:/public
spring.resources.static-locations=classpath:/META-INF/resources,classpath:/META-INF/resources/webjars,classpath:/resources,classpath:/static,classpath:/public

igw.dynamic-data-source.scan-package-path=com.igw
igw.dynamic-data-source.auto-use-default-data-source-if-not-found=true

#kafka应用id
kafkaAgentid=1000007
#企业ID
corpid=wwd5dfcb62e3046964
#开发者ID
corpsecret=l7poSvS7YvEw-PCbSLiGz6177c6E0FsttjCw9DJYApM