#数据源1
spring.datasource.master.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.master.jdbc-url=jdbc:oracle:thin:@10.86.229.182:1521:igwdvpoa
spring.datasource.master.username=pubcde
spring.datasource.master.password=pubcde_1234
spring.datasource.master.default-datasource=true

#数据源2，数据中心
spring.datasource.slave.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.slave.jdbc-url=jdbc:oracle:thin:@(description =(address = (protocol = tcp)(host =10.86.229.133)(port = 1521))(address = (protocol = tcp)(host =10.86.229.134)(port = 1521))(load_balance=yes)(connect_data =(service_name = igwdc)))
spring.datasource.slave.username=customer
spring.datasource.slave.password=wi_golf1
spring.datasource.slave.default-datasource=false

#数据源3，#OA
spring.datasource.oa.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.oa.jdbc-url=jdbc:sqlserver://10.86.228.15:1433;DatabaseName=ecology
spring.datasource.oa.username=sa
spring.datasource.oa.password=weaver
spring.datasource.oa.default-datasource=false


#===================LC系统配置开始=========================
#kafka
zookeeper.connect=10.86.227.81:2181
broker.list=10.86.227.81:9092

# 发公司内部系统  公司内部相关人员邮箱地址
expire_staff_remind_address=weinn@igwfmc.com
#抄送人邮箱
expire_staff_copy_address=liwen@igwfmc.com

#redis IP
redisReadURL=10.86.227.89
#redis 端口
redisReadPort=6379
#redis 密码
redis.password=root