log4j.rootCategory=INFO, stdout,common-all,common-warn,common-error

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.conversionPattern= %d  %-5p %t %c    %m%n


log4j.appender.common-all=org.apache.log4j.DailyRollingFileAppender
log4j.appender.common-all.file=/home/fuzw/igw-logs/common-all.log
log4j.appender.common-all.layout=org.apache.log4j.PatternLayout
log4j.appender.common-all.layout.conversionPattern= %d  %-5p %t %c    %m%n


log4j.appender.common-warn=org.apache.log4j.DailyRollingFileAppender
log4j.appender.common-warn.file=/home/fuzw/igw-logs/common-warn.log
log4j.appender.common-warn.layout=org.apache.log4j.PatternLayout
log4j.appender.common-warn.threshold=WARN
log4j.appender.common-warn.layout.conversionPattern= %d  %-5p %t %c    %m%n


log4j.appender.common-error=org.apache.log4j.DailyRollingFileAppender
log4j.appender.common-error.file=/home/fuzw/igw-logs/common-error.log
log4j.appender.common-error.layout=org.apache.log4j.PatternLayout
log4j.appender.common-error.threshold=ERROR
log4j.appender.common-error.layout.conversionPattern= %d  %-5p %t %c   %m%n

log4j.logger.com.springframework=DEBUG
log4j.logger.com.ibatis=DEBUG
log4j.logger.com.ibatis.common.jdbc.SimpleDataSource=DEBUG
log4j.logger.com.ibatis.common.jdbc.ScriptRunner=DEBUG
log4j.logger.com.ibatis.sqlmap.engine.impl.SqlMapClientDelegate=DEBUG
log4j.logger.com.ibatis.SQL=trace

log4j.logger.java.sql.Connection=DEBUG
log4j.logger.java.sql.Statement=TRACE
log4j.logger.java.sql.PreparedStatement=TRACE
log4j.logger.java.sql.ResultSet=DEBUG
log4j.logger.java.sql=DEBUG
log4j.logger.com.igw.base=DEBUG
log4j.logger.com.igw.lc.common.dao=TRACE
log4j.logger.com.igw.lc.xbrl.dao=TRACE
log4j.logger.com.igw.market.file.dao=TRACE
log4j.logger.com.igw.market.query.dao=TRACE
