#数据源1
spring.datasource.master.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.master.jdbc-url=jdbc:oracle:thin:@10.86.140.24:1521:igwdvpoa
spring.datasource.master.username=customer
spring.datasource.master.password=customer
spring.datasource.master.default-datasource=true

#数据源2 恒生
spring.datasource.hangseng.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.hangseng.jdbc-url=jdbc:oracle:thin:@(description =(address = (protocol = tcp)(host =10.86.229.123)(port = 1521))(address = (protocol = tcp)(host =10.86.229.124)(port = 1521))(load_balance=yes)(connect_data =(service_name = igwdc)))
spring.datasource.hangseng.username=customer
spring.datasource.hangseng.password=wi_golf1
spring.datasource.hangseng.default-datasource=false


# 指定kafka 代理地址，可以多个
spring.kafka.bootstrap-servers=10.86.144.2:9092
#-------------- provider 开始 --------------
spring.kafka.producer.retries=0
# 每次批量发送消息的数量
spring.kafka.producer.batch-size=16384
spring.kafka.producer.buffer-memory=33554432
# 指定消息key和消息体的编解码方式
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
#-------------- provider 结束 --------------
#-------------- consumer 开始 --------------
# 指定默认消费者group id
spring.kafka.consumer.group-id=test-hello-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.consumer.auto-commit-interval=100
# 指定消息key和消息体的编解码方式
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
 
#=================== redis集群配置 开始 =========================
#集群节点地址
spring.redis.cluster.nodes=10.86.144.2:6379,10.86.144.2:6380,10.86.144.3:6379,10.86.144.3:6380,10.86.144.4:6379,10.86.144.4:6380
#获取失败时最大重定向次数
spring.redis.cluster.max-redirects=3
#连接池最大连接数（使用负值表示没有限制）
spring.redis.pool.max-active=1000
#连接池中的最大空闲连接
spring.redis.pool.max-idle=10
#连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.pool.max-wait=-1
#连接池中的最小空闲连接
spring.redis.pool.min-idle=5
spring.redis.password=passwd123
#连接超时时长（毫秒）
spring.redis.timeout=6000
#=================== redis集群配置 结束 =========================

#=================== Quartz配置开始 =========================
#是否自动启动JobScheduler
igw.quartz.auto-startup=true

#每天晚上11点  统计订阅人数,退订人数
push.cron.subscriptionyJob = 0 0 23 * * ?
#=================== Quartz配置结束 =========================

#微信代码 1生产2测试
wechat_code=2

#模板地址
template_path=/home/liw/template/

#文件服务器
file_server=http://10.86.144.18:8088/ItApp-Common-FileServer/

#基础数据服务地址(已不维护此服务,后续新接口都在csdcl1服务)
common_data=http://10.86.144.19:8082/ItApp-Invest-CommonData/

#csdcl1基础数据服务地址
csdcl1_data=http://10.86.144.19:8184/ItApp-AppData-CSDCL1Data/

#中登成交汇总文件
aggr_path=/home/liw/aggr/YYYYMMDD/

#=================== spring-cloud相关配置 开始 =========================
spring.application.name=ItApp-Market-Customer
spring.cloud.consul.host=10.86.144.2
spring.cloud.consul.port=8500
spring.cloud.discovery.enabled=true
spring.cloud.consul.discovery.heartbeat.enabled=true
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.deregister=true
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.service-name=${spring.application.name}
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
#=================== spring-cloud相关配置 结束 =========================

#公众号应用id
weixin.appid=wx65c246e87c5d68c5
#公众号秘钥
weixin.appsecret=26e833269c5546d0646a44b29f80c5f8
#分红通知模板id
#dividend.notice.template=0v746L2zOIhnZMMOvONNiuos2z1F8E0RDzg9QnT4eiM
dividend.notice.template=5uNdr-wMw4A-gEpDwJjSvCrVmFpTLB-RRLS0eOHlzyU
#测试推送用户
user.openid=o9SnIt9z8kDMQerUYlT71ghEy01E;o9SnIt1yyxbjcUdTlMa4ufnW4EdI;o9SnItzQLJI4kjlU8u5jLA4QZ5-M;o9SnIt3nT9jO0bsuQqMOgVxyjnKY

#获取access_token 地址
access_token.address=http://10.86.140.56:8097/woaservice/wx/getWechatAccessToken