CREATE TABLE FUNDDIVIDEND (
	SYS_ID VARCHAR2(100) DEFAULT sys_guid() NOT NULL ,
	SENT_DATE VARCHAR2(100),
	SENT_TIME VARCHAR2(100),
	FILTER_AMOUNT VARCHAR2(100),
	MESSAGE_BEGIN VARCHAR2(100),
	FUND_NAME VARCHAR2(100),
	FUND_CODE VARCHAR2(100),
	NOTICE_NAME VARCHAR2(100),
	MESSAGE_END VARCHAR2(100),
	MESSAGE_HREF VARCHAR2(100),
	PROMPT_TYPE VARCHAR2(100),
	SENT_STATUS VARCHAR2(100),
	REVIEW_STATUS VARCHAR2(100),
	CREATED_USER VARCHAR2(100),
	CREATED_DATE DATE,
	UPDATED_USER VARCHAR2(100),
	UPDATED_DATE DATE,
	VALID_FLAG VARCHAR2(1) DEFAULT '0'
);
COMMENT ON TABLE PUBCDE.FUNDDIVIDENDD IS '基金分红通知模板';
COMMENT ON COLUMN PUBCDE.FUNDDIVIDENDD.SYS_ID IS '主键';
COMMENT ON COLUMN PUBCDE.FUNDDIVIDENDD.SENT_DATE IS '发送日期';
COMMENT ON COLUMN PUBCDE.FUNDDIVIDENDD.SENT_TIME IS '发送时间';
COMMENT ON COLUMN PUBCDE.FUNDDIVIDENDD.FILTER_AMOUNT IS '筛选金额';
COMMENT ON COLUMN PUBCDE.FUNDDIVIDENDD.MESSAGE_BEGIN IS '消息开头';
COMMENT ON COLUMN PUBCDE.FUNDDIVIDENDD.FUND_NAME IS '基金名称';
COMMENT ON COLUMN PUBCDE.FUNDDIVIDENDD.FUND_CODE IS '基金代码';
COMMENT ON COLUMN PUBCDE.FUNDDIVIDEND.NOTICE_NAME IS '公告名称';
COMMENT ON COLUMN PUBCDE.FUNDDIVIDENDD.MESSAGE_END IS '消息结尾';
COMMENT ON COLUMN PUBCDE.FUNDDIVIDENDD.MESSAGE_HREF IS '消息连接';
COMMENT ON COLUMN PUBCDE.FUNDDIVIDENDD.PROMPT_TYPE IS '提示类型';
COMMENT ON COLUMN PUBCDE.FUNDDIVIDENDD.SENT_STATUS IS '发送状态';
COMMENT ON COLUMN PUBCDE.FUNDDIVIDENDD.REVIEW_STATUS IS '复核状态';
COMMENT ON COLUMN PUBCDE.FUNDDIVIDENDD.CREATED_USER IS '创建人';
COMMENT ON COLUMN PUBCDE.FUNDDIVIDENDD.CREATED_DATE IS '创建时间';
COMMENT ON COLUMN PUBCDE.FUNDDIVIDENDD.UPDATED_USER IS '更新人';
COMMENT ON COLUMN PUBCDE.FUNDDIVIDENDD.UPDATED_DATE IS '更新时间';
COMMENT ON COLUMN PUBCDE.FUNDDIVIDENDD.VALID_FLAG IS '是否有效(0-有效,1-无效)';