CREATE TABLE "PUBCDE"."FUNDDIVIDEND" 
   (	"SYS_ID" VARCHAR2(100) DEFAULT sys_guid() NOT NULL ENABLE, 
	"SENT_DATE" VARCHAR2(100), 
	"SENT_TIME" VARCHAR2(100), 
	"FILTER_AMOUNT" VARCHAR2(100), 
	"MESSAGE_BEGIN" VARCHAR2(100), 
	"FUND_NAME" VARCHAR2(100), 
	"MESSAGE_END" VARCHAR2(100), 
	"MESSAGE_HREF" VARCHAR2(100), 
	"PROMPT_TYPE" VARCHAR2(100), 
	"SENT_STATUS" VARCHAR2(100), 
	"REVIEW_STATUS" VARCHAR2(100), 
	"CREATED_USER" VARCHAR2(100), 
	"CREATED_DATE" DATE, 
	"UPDATED_USER" VARCHAR2(100), 
	"UPDATED_DATE" DATE, 
	"VALID_FLAG" VARCHAR2(1) DEFAULT '0', 
	"FUND_CODE" VARCHAR2(100), 
	"NOTICE_NAME" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PUBCDE" ;

COMMENT ON TABLE PUBCDE.FUNDDIVIDEND IS '基金分红通知模板';
COMMENT ON COLUMN PUBCDE.FUNDDIVIDEND.SYS_ID IS '主键'
COMMENT ON COLUMN PUBCDE.FUNDDIVIDEND.SENT_DATE IS '发送日期'
COMMENT ON COLUMN PUBCDE.FUNDDIVIDEND.SENT_TIME IS '发送时间'
COMMENT ON COLUMN PUBCDE.FUNDDIVIDEND.FILTER_AMOUNT IS '筛选金额'
COMMENT ON COLUMN PUBCDE.FUNDDIVIDEND.MESSAGE_BEGIN IS '消息开头'
COMMENT ON COLUMN PUBCDE.FUNDDIVIDEND.FUND_NAME IS '基金名称'
COMMENT ON COLUMN PUBCDE.FUNDDIVIDEND.MESSAGE_END IS '消息结尾'
COMMENT ON COLUMN PUBCDE.FUNDDIVIDEND.MESSAGE_HREF IS '消息连接'
COMMENT ON COLUMN PUBCDE.FUNDDIVIDEND.PROMPT_TYPE IS '提示类型'
COMMENT ON COLUMN PUBCDE.FUNDDIVIDEND.SENT_STATUS IS '发送状态'
COMMENT ON COLUMN PUBCDE.FUNDDIVIDEND.REVIEW_STATUS IS '复核状态'
COMMENT ON COLUMN PUBCDE.FUNDDIVIDEND.CREATED_USER IS '创建人'
COMMENT ON COLUMN PUBCDE.FUNDDIVIDEND.CREATED_DATE IS '创建时间'
COMMENT ON COLUMN PUBCDE.FUNDDIVIDEND.UPDATED_USER IS '更新人'
COMMENT ON COLUMN PUBCDE.FUNDDIVIDEND.UPDATED_DATE IS '更新时间'
COMMENT ON COLUMN PUBCDE.FUNDDIVIDEND.VALID_FLAG IS '是否有效(0-有效,1-无效)'
COMMENT ON COLUMN PUBCDE.FUNDDIVIDEND.FUND_CODE IS '基金代码'
COMMENT ON COLUMN PUBCDE.FUNDDIVIDEND.NOTICE_NAME IS '公告名称'